#pragma once

#include "include.hpp"

void correctAnswerFrance(int* indexCounter, Color* firstColor, Color* secondColor, int* dialogueProgress);
void renderRabbit(Vector2* rabbitPosition, int* rabbitDirection, int frame, Texture2D* front, Texture2D* frontIdle, Texture2D* frontWalk1, Texture2D* frontWalk2, Texture2D* left, Texture2D* left2, Texture2D* leftWalk2, Texture2D* right, Texture2D* right2, Texture2D* rightWalk2, Texture2D* back, Texture2D* backIdle, Texture2D* backWalk1, Texture2D* backWalk2);
void renderTutorial(GameScreen* state, Vector2* rabbitPosition, int* rabbitDirection, int frame, Texture2D* front, Texture2D* frontIdle, Texture2D* frontWalk1, Texture2D* frontWalk2, Texture2D* left, Texture2D* left2, Texture2D* leftWalk2, Texture2D* right, Texture2D* right2, Texture2D* rightWalk2, Texture2D* back, Texture2D* backIdle, Texture2D* backWalk1, Texture2D* backWalk2, Texture2D* background, Texture2D* goal);
void renderItaly(GameScreen* state, Vector2* rabbitPosition, Vector2* fish1Position, Vector2* fish2Position, Vector2* fish3Position, int frame, Texture2D* front, Texture2D* front2, Texture2D* front3, Texture2D background1, Texture2D background2, Texture2D background3, Texture2D fish1, Texture2D fish2, Texture2D fish3, Texture2D fish1ani, Texture2D fish2ani, Texture2D fish3ani, bool* isCompleted);
void renderFrance(GameScreen* state, bool* isFrench, bool* isFrenchTalking, Texture2D* background, Texture2D* girlIdle, Texture2D* girlTalk, Texture2D* rabbitIdle, Texture2D* textbox, int* dialogueProgress, Color *firstColor, Color *secondColor, int* indexCounter, questionPts* isCorrect, questionPts* tempCorrect, bool* isCompleted);
void renderSpain(GameScreen* state, int* choice, Texture2D background, Texture2D rabbit, Texture2D outfit1, Texture2D outfit2, Texture2D outfit3, Texture2D outfit4, Texture2D outfit5, Texture2D outfit6, Texture2D outfit7);
void renderBulgaria(GameScreen* state, Vector2* rabbitPosition, int* rabbitDirection, int frame, Texture2D* front, Texture2D* frontIdle, Texture2D* frontWalk1, Texture2D* frontWalk2, Texture2D* left, Texture2D* left2, Texture2D* leftWalk2, Texture2D* right, Texture2D* right2, Texture2D* rightWalk2, Texture2D* back, Texture2D* backIdle, Texture2D* backWalk1, Texture2D* backWalk2, Texture2D* background, Texture2D* goal);
void collisionCheck(Rectangle rec, Vector2* rabbitPosition, int *rabbitDirection, int radius);